// Copyright 2026 the LayerStack Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Writes the `layerstack_schemas` tables for a [`Model`].

use std::collections::BTreeMap;
use std::fmt::Write as _;

use layerstack::{PropertyKind, SchemaKind, TokenInterner, Value, Variability};

use crate::model::{Domain, Model, Property};

/// The year the generated files' copyright line names. Fixed, so that
/// regenerating from the same sources writes the same files.
const COPYRIGHT_YEAR: u32 = 2026;

/// The generated files, as `(file name, contents)`, with a value this
/// generation cannot express listed as an error.
pub(crate) fn files(model: &Model) -> Result<Vec<(String, String)>, String> {
    let mut types = ValueTypes::default();
    let mut failures = Vec::new();
    let mut files = Vec::new();
    for domain in &model.domains {
        files.push((
            format!("{}.rs", module(domain.plugin)),
            domain_file(model, domain, &mut types, &mut failures),
        ));
    }
    if !failures.is_empty() {
        return Err(format!(
            "values layerstack_schemas cannot express:\n{}",
            failures.join("\n")
        ));
    }
    files.insert(0, ("mod.rs".into(), mod_file(model, &types)));
    Ok(files)
}

/// The header of every generated file.
fn header(model: &Model) -> String {
    format!(
        "// Copyright 2016 Pixar\n\
         // Copyright {COPYRIGHT_YEAR} the LayerStack Authors\n\
         // SPDX-License-Identifier: LicenseRef-TOST-1.0\n\
         //\n\
         // Generated by `layerstack_schemagen` from the schema definitions of OpenUSD\n\
         // {version} (the usd-core {version} wheel), which are licensed under the\n\
         // Tomorrow Open Source Technology License 1.0; see `LICENSE-TOST-1.0` and\n\
         // `NOTICE`. Do not edit: regenerate with\n\
         // `cargo run -p layerstack_schemagen -- --pxr <site-packages>/pxr`.\n",
        version = model.version
    )
}

/// The Rust module of a plugin (`usdGeom` → `usd_geom`).
fn module(plugin: &str) -> String {
    let mut out = String::new();
    for c in plugin.chars() {
        if c.is_ascii_uppercase() {
            out.push('_');
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

fn mod_file(model: &Model, types: &ValueTypes) -> String {
    let mut out = header(model);
    out.push_str("//\n// Sources:\n");
    for file in &model.files {
        let _ = writeln!(out, "// - `{file}`");
    }
    out.push_str("\n//! The generated tables.\n\n@IMPORTS@\n");
    for domain in &model.domains {
        let _ = writeln!(out, "mod {};", module(domain.plugin));
    }
    let _ = write!(
        out,
        "\n/// The OpenUSD release whose schemas these are.\n\
         pub const OPENUSD_VERSION: &str = {:?};\n\n",
        model.version
    );

    out.push_str(
        "/// A domain of OpenUSD schemas: the schemas one OpenUSD plugin defines.\n\
         ///\n\
         /// Spec: AOUSD Core §13.1 leaves how schemas are defined to the\n\
         /// implementation; these are OpenUSD's.\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n\
         #[non_exhaustive]\n\
         pub enum Domain {\n",
    );
    for domain in &model.domains {
        let _ = writeln!(out, "    /// OpenUSD's `{}` schemas.", domain.plugin);
        if !domain.left_out.is_empty() {
            out.push_str("    ///\n    /// Leaves out, having no prim definition:\n");
            for (name, why) in &domain.left_out {
                let _ = writeln!(out, "    /// - `{name}`, {why}.");
            }
        }
        let _ = writeln!(out, "    {},", domain.variant);
    }
    out.push_str(
        "}\n\nimpl Domain {\n    /// Every domain.\n    pub const ALL: &'static [Self] = &[",
    );
    for domain in &model.domains {
        let _ = write!(out, "Self::{}, ", domain.variant);
    }
    out.push_str(
        "];\n\n    /// The OpenUSD plugin the domain's schemas come from (`usdGeom`).\n    \
         #[must_use]\n    pub fn plugin(self) -> &'static str {\n        match self {\n",
    );
    for domain in &model.domains {
        let _ = writeln!(
            out,
            "            Self::{} => {:?},",
            domain.variant, domain.plugin
        );
    }
    out.push_str(
        "        }\n    }\n\n    /// The other domains whose schemas this domain's schemas inherit from,\n    \
         /// include or auto-apply to.\n    #[must_use]\n    \
         pub fn dependencies(self) -> &'static [Self] {\n        match self {\n",
    );
    for domain in &model.domains {
        let variants: Vec<String> = domain
            .dependencies
            .iter()
            .map(|plugin| {
                let variant = model
                    .domains
                    .iter()
                    .find(|d| d.plugin == *plugin)
                    .expect("dependency is generated")
                    .variant;
                format!("Self::{variant}")
            })
            .collect();
        let _ = writeln!(
            out,
            "            Self::{} => &[{}],",
            domain.variant,
            variants.join(", ")
        );
    }
    out.push_str(
        "        }\n    }\n\n    pub(crate) fn tables(self) -> &'static DomainTables {\n        match self {\n",
    );
    for domain in &model.domains {
        let _ = writeln!(
            out,
            "            Self::{} => &{}::TABLES,",
            domain.variant,
            module(domain.plugin)
        );
    }
    out.push_str("        }\n    }\n}\n");

    for (ident, (name, is_array, zero)) in &types.statics {
        let _ = write!(
            out,
            "\npub(crate) static {ident}: ValueType = ValueType {{\n    \
             name: {name:?},\n    is_array: {is_array},\n    zero: {},\n}};\n",
            closure(zero)
        );
    }
    let arc = if out.contains("Arc::from(") {
        "use alloc::sync::Arc;\n\n"
    } else {
        ""
    };
    out.replace(
        "@IMPORTS@\n",
        &format!(
            "{arc}use layerstack::Value;\n\nuse crate::table::{{DomainTables, ValueType}};\n\n"
        ),
    )
}

/// The value types the domains declare, each emitted once in `mod.rs`.
#[derive(Default)]
struct ValueTypes {
    /// Static name → (type name, is array, the zero value's expression).
    statics: BTreeMap<String, (String, bool, String)>,
}

impl ValueTypes {
    /// The static naming `(name, is_array)`.
    fn get(&mut self, name: &str, is_array: bool, zero: String) -> String {
        let base = name.strip_suffix("[]").unwrap_or(name);
        let mut ident: String = base.to_ascii_uppercase();
        if is_array {
            ident.push_str("_ARRAY");
        }
        self.statics
            .entry(ident.clone())
            .or_insert((name.into(), is_array, zero));
        ident
    }
}

fn domain_file(
    model: &Model,
    domain: &Domain,
    types: &mut ValueTypes,
    failures: &mut Vec<String>,
) -> String {
    let mut out = header(model);
    let _ = write!(
        out,
        "\n//! OpenUSD's `{}` schemas.\n\n\
         #![allow(\n    clippy::unreadable_literal,\n    clippy::approx_constant,\n    \
         clippy::excessive_precision,\n    reason = \"values as OpenUSD writes them\"\n)]\n\n\
         @IMPORTS@\n\
         pub(crate) static TABLES: DomainTables = DomainTables {{\n    schemas: &[\n",
        domain.plugin
    );
    for schema in &domain.schemas {
        let kind = match schema.kind {
            SchemaKind::ConcreteTyped => "ConcreteTyped",
            SchemaKind::AbstractTyped => "AbstractTyped",
            SchemaKind::SingleApplyApi => "SingleApplyApi",
            SchemaKind::MultipleApplyApi => "MultipleApplyApi",
        };
        let _ = write!(
            out,
            "        Schema {{\n            name: {:?},\n            kind: SchemaKind::{kind},\n            \
             parent: {:?},\n            built_ins: &{:?},\n            properties: &[\n",
            schema.name, schema.parent, schema.built_ins
        );
        for property in &schema.properties {
            property_entry(&mut out, model, &schema.name, property, types, failures);
        }
        out.push_str("            ],\n            overrides: &[\n");
        for property in &schema.overrides {
            property_entry(&mut out, model, &schema.name, property, types, failures);
        }
        out.push_str("            ],\n        },\n");
    }
    out.push_str("    ],\n    auto_applies: &[\n");
    for (schema, target) in &domain.auto_applies {
        let _ = writeln!(out, "        ({schema:?}, {target:?}),");
    }
    out.push_str("    ],\n};\n");
    let mut imports = String::new();
    if out.contains("Arc::from(") {
        imports.push_str("use alloc::sync::Arc;\n\n");
    }
    let values = if out.contains("Value::") {
        "Value, "
    } else {
        ""
    };
    let _ = write!(
        imports,
        "use layerstack::{{PropertyKind, SchemaKind, {values}Variability}};\n\n"
    );
    let fallback = if out.contains("fallback(|") {
        ", fallback"
    } else {
        ""
    };
    let _ = write!(
        imports,
        "use crate::table::{{DomainTables, Property, Schema{fallback}}};\n\n"
    );
    out.replace("@IMPORTS@\n", &imports)
}

fn property_entry(
    out: &mut String,
    model: &Model,
    schema: &str,
    property: &Property,
    types: &mut ValueTypes,
    failures: &mut Vec<String>,
) {
    let kind = match property.kind {
        PropertyKind::Attribute => "Attribute",
        PropertyKind::Relationship => "Relationship",
    };
    let value_type = match &property.value_type {
        None => "None".to_string(),
        Some((name, is_array, zero)) => match expr(zero, &model.tokens) {
            Ok(zero) => format!("Some(&super::{})", types.get(name, *is_array, zero)),
            Err(why) => {
                failures.push(format!("{schema}.{}: type {name}: {why}", property.name));
                "None".into()
            }
        },
    };
    let fallback = match &property.fallback {
        None => "None".to_string(),
        Some(value) => match expr(value, &model.tokens) {
            Ok(value) => format!("fallback({})", closure(&value)),
            Err(why) => {
                failures.push(format!("{schema}.{}: fallback: {why}", property.name));
                "None".into()
            }
        },
    };
    let variability = match property.variability {
        Variability::Varying => "Varying",
        Variability::Uniform => "Uniform",
    };
    let _ = write!(
        out,
        "                Property {{\n                    name: {:?},\n                    \
         kind: PropertyKind::{kind},\n                    value_type: {value_type},\n                    \
         variability: Variability::{variability},\n                    fallback: {fallback},\n                \
         }},\n",
        property.name
    );
}

/// A closure constructing `expr` from the caller's token interner.
fn closure(expr: &str) -> String {
    if expr.contains("t.intern(") {
        format!("|t| {expr}")
    } else {
        format!("|_| {expr}")
    }
}

/// A Rust expression constructing `value`, whose tokens intern into `t`.
fn expr(value: &Value, tokens: &TokenInterner) -> Result<String, String> {
    fn list<T>(items: &[T], each: impl Fn(&T) -> String) -> String {
        let items: Vec<String> = items.iter().map(each).collect();
        format!("[{}]", items.join(", "))
    }
    Ok(match value {
        Value::Null => "Value::Null".into(),
        Value::Bool(v) => format!("Value::Bool({v})"),
        Value::UChar(v) => format!("Value::UChar({v})"),
        Value::Int(v) => format!("Value::Int({v})"),
        Value::UInt(v) => format!("Value::UInt({v})"),
        Value::Int64(v) => format!("Value::Int64({v})"),
        Value::UInt64(v) => format!("Value::UInt64({v})"),
        Value::Half(v) => format!("Value::Half({v:#06x})"),
        Value::Float(v) => format!("Value::Float({})", f32_lit(*v)),
        Value::Double(v) => format!("Value::Double({})", f64_lit(*v)),
        Value::String(v) => format!("Value::String(Arc::from({:?}))", &**v),
        Value::Token(v) => format!("Value::Token(t.intern({:?}))", tokens.resolve(*v)),
        Value::Asset(v) => format!("Value::Asset(Arc::from({:?}))", &**v),
        Value::PathExpression(v) => format!("Value::PathExpression(Arc::from({:?}))", &**v),
        Value::TimeCode(v) => format!("Value::TimeCode({})", f64_lit(*v)),
        Value::Vec2d(v) => format!("Value::Vec2d({})", list(v, |x| f64_lit(*x))),
        Value::Vec3d(v) => format!("Value::Vec3d({})", list(v, |x| f64_lit(*x))),
        Value::Vec4d(v) => format!("Value::Vec4d({})", list(v, |x| f64_lit(*x))),
        Value::Vec2f(v) => format!("Value::Vec2f({})", list(v, |x| f32_lit(*x))),
        Value::Vec3f(v) => format!("Value::Vec3f({})", list(v, |x| f32_lit(*x))),
        Value::Vec4f(v) => format!("Value::Vec4f({})", list(v, |x| f32_lit(*x))),
        Value::Vec2h(v) => format!("Value::Vec2h({})", list(v, |x| format!("{x:#06x}"))),
        Value::Vec3h(v) => format!("Value::Vec3h({})", list(v, |x| format!("{x:#06x}"))),
        Value::Vec4h(v) => format!("Value::Vec4h({})", list(v, |x| format!("{x:#06x}"))),
        Value::Vec2i(v) => format!("Value::Vec2i({})", list(v, ToString::to_string)),
        Value::Vec3i(v) => format!("Value::Vec3i({})", list(v, ToString::to_string)),
        Value::Vec4i(v) => format!("Value::Vec4i({})", list(v, ToString::to_string)),
        Value::Matrix2d(v) => format!(
            "Value::Matrix2d(alloc::boxed::Box::new({}))",
            list(&v[..], |x| f64_lit(*x))
        ),
        Value::Matrix3d(v) => format!(
            "Value::Matrix3d(alloc::boxed::Box::new({}))",
            list(&v[..], |x| f64_lit(*x))
        ),
        Value::Matrix4d(v) => format!(
            "Value::Matrix4d(alloc::boxed::Box::new({}))",
            list(&v[..], |x| f64_lit(*x))
        ),
        Value::Quatd(v) => format!("Value::Quatd({})", list(v, |x| f64_lit(*x))),
        Value::Quatf(v) => format!("Value::Quatf({})", list(v, |x| f32_lit(*x))),
        Value::Quath(v) => format!("Value::Quath({})", list(v, |x| format!("{x:#06x}"))),
        Value::Array(items) => {
            let items = items
                .iter()
                .map(|item| expr(item, tokens))
                .collect::<Result<Vec<_>, _>>()?;
            format!("Value::Array(alloc::vec![{}])", items.join(", "))
        }
        Value::Dictionary(entries) => {
            let entries = entries
                .iter()
                .map(|(key, item)| {
                    Ok(format!(
                        "(Arc::from({:?}), {})",
                        &**key,
                        expr(item, tokens)?
                    ))
                })
                .collect::<Result<Vec<_>, String>>()?;
            format!("Value::Dictionary(alloc::vec![{}])", entries.join(", "))
        }
        other => return Err(format!("no constructor for {other:?}")),
    })
}

fn f32_lit(v: f32) -> String {
    if v.is_nan() {
        "f32::NAN".into()
    } else if v.is_infinite() {
        if v > 0.0 {
            "f32::INFINITY"
        } else {
            "f32::NEG_INFINITY"
        }
        .into()
    } else {
        format!("{v:?}")
    }
}

fn f64_lit(v: f64) -> String {
    if v.is_nan() {
        "f64::NAN".into()
    } else if v.is_infinite() {
        if v > 0.0 {
            "f64::INFINITY"
        } else {
            "f64::NEG_INFINITY"
        }
        .into()
    } else {
        format!("{v:?}")
    }
}
